### ISSUE TITLE
Phenix will say pre_start ran even though that function doesn't exist

### ISSUE THREAD

**Issue by c-abate** [sandia-minimega/phenix#51]
I had an app that I was converting from v5 to v6. In v5 the "pre start" function was named `start`.  I didn't change this to `pre_start` and found that the `phenix experiment start` output still said it ran the pre_start function even though it didn't run.

**Comment by activeshadow** [comment]
@c-abate I'm assuming the app in question was written in Python. The `pre_start` function is implemented in the parent class and just does a `pass`. As such, there's no way for the parent class to know if it wasn't actually implemented. We can't do something like raise a `not implemented error` because this would assume every app will implement the `pre_start` function and we don't want to require that.
